name: game
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flame: ^1.13.1
  flame_audio: ^2.1.6
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_fonts: ^6.1.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/audio/
  uses-material-design: true
